#!/bin/bash
# postrm: freenas-proxmox v3.x removal script
# Removes the TrueNAS custom storage plugin for Proxmox VE.
set -e

PLUGIN_DST="/usr/share/perl5/PVE/Storage/Custom/TrueNAS.pm"
LOG_FILE="/var/log/freenas-proxmox-install.log"

log() {
    echo "[freenas-proxmox] $*" | tee -a "$LOG_FILE"
}

restart_pve_services() {
    log "Restarting Proxmox VE services ..."
    pvedaemon restart && log "pvedaemon restarted"
    pveproxy restart  && log "pveproxy restarted"
}

case "$1" in
    remove)
        log "Removing freenas-proxmox ..."
        rm -f "$PLUGIN_DST"
        log "Plugin removed"
        restart_pve_services
        log "freenas-proxmox removed. Refresh your Proxmox browser tab."
        ;;
    purge)
        log "Purging freenas-proxmox ..."
        rm -f "$PLUGIN_DST"
        rm -f "$LOG_FILE"
        ;;
    upgrade|failed-upgrade|disappear|abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "$0: called with unknown argument '$1'" >&2
        exit 0
        ;;
esac

exit 0
